### PR TITLE
add support for dart-sass

### PR DESCRIPTION
**Pull request by hackeryarn**
This adds `dart-sass` as a target.

### CODE REVIEW

**Comment by tuhlmann** [comment]
@hackeryarn Thank you for contributing this PR!

I'm afraid this repository is not maintained anymore as I don't work with Clojure anymore. If you would like to continue it, please create a fork of it.

Sorry for any caused confusion!

**Comment by hackeryarn** [comment]
@tuhlmann thank you for the reply. I totally understand. Would you be willing/able to add me to the Clojars group for the project? I am happy to take over maintenance, on my fork, since I use this daily.

Here is a link to my Clojars account https://clojars.org/users/acher.

**Comment by tuhlmann** [comment]
@hackeryarn Thanks for your willingness to take over!
I'll have to look into Clojars groups and how the project is named. The goal should be to remove me completely from this Clojars project and completely hand it over to you. Do you know if that's possible and maybe can share a link with a description on the topic?

Thanks!

**Comment by hackeryarn** [comment]
@tuhlmann I can't find the official guide, but here are the rough steps:

- Log into Clojars
- Go to Dashboard in the top nav 
- Click on the `lein-sass` group listed under "Your Groups"
- Add me as an admin member

At that point, I should be able to remove you completely, if you wish. I don't think you can remove yourself from a group, as strange as that is.

**Comment by tuhlmann** [comment]
@hackeryarn I just checked clojars- turns out I'm not the admin of the group but stephanos, the original contributor is here: https://github.com/stephanos/lein-sass.

I'm afraid you'll have to ask him to add you.

**Comment by hackeryarn** [comment]
@stephanos Would you be willing/able to add me to the Clojars group for `lein-sass`? I provided some instruction here https://github.com/tuhlmann/lein-sass/pull/4#issuecomment-1742127245 just in case it has been a while since you've used Clojars.

I am also happy to take over the admin duties of the Clojars group and see the project forward. I still use this daily and will continue to for the foreseeable future.

**Comment by stephanos** [comment]
@hackeryarn done!

**Comment by hackeryarn** [comment]
@stephanos thanks for the quick response, but it doesn't look like I have access to the group.

Did you add the right use in Clojars? I am sorry that I did not include the link to my account from a previous message in this PR.  https://clojars.org/users/acher

**Comment by stephanos** [comment]
@hackeryarn oops, sorry - should have read it more carefully. I had made `tuhlmann` admin. Fixed now!

**Comment by hackeryarn** [comment]
@stephanos thank you so much. Looks like it all went through now.

**Pull request closed without merging**
